import React, { useState } from 'react'
import type { DirectionCard as DirectionCardType } from '@/api/client'
import ScoreDial from '@/components/ScoreDials'

interface Props {
  cards: DirectionCardType[]
  loading: boolean
  draftDistinctiveness?: number | null
  draftVoiceMatch?: number | null
}

export default function DirectionCards({ cards, loading, draftDistinctiveness, draftVoiceMatch }: Props) {
  const [copied, setCopied] = useState<string | null>(null)
  const [expanded, setExpanded] = useState<string | null>(null)

  function handleCopy(text: string, persona: string) {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(persona)
      setTimeout(() => setCopied(null), 2000)
    })
  }

  if (loading) {
    return (
      <div style={styles.grid}>
        {[0, 1, 2].map(i => (
          <div key={i} style={{ ...styles.card, ...styles.skeleton }}>
            <div style={styles.skeletonLine} />
            <div style={{ ...styles.skeletonLine, width: '60%' }} />
            <div style={{ ...styles.skeletonLine, marginTop: '12px' }} />
            <div style={{ ...styles.skeletonLine, width: '85%' }} />
            <div style={{ ...styles.skeletonLine, width: '70%' }} />
          </div>
        ))}
      </div>
    )
  }

  if (cards.length === 0) {
    return (
      <div style={styles.empty}>
        <div style={styles.emptyIcon}>↑</div>
        <p>Paste a draft and hit <strong>Analyse</strong> to generate divergent directions.</p>
      </div>
    )
  }

  return (
    <div style={styles.grid}>
      {cards.map(card => {
        const isExpanded = expanded === card.persona
        const hasFaithIssue = card.faithfulness < 80
        const wasRefined = card.refined

        return (
          <div key={card.persona} style={styles.card}>
            {/* Header row */}
            <div style={styles.cardHeader}>
              <div style={{ flex: 1 }}>
                <div style={styles.personaRow}>
                  <span style={styles.personaLabel}>{card.persona}</span>
                  {wasRefined && (
                    <span style={styles.refinedBadge} title="Regenerated by refine loop">refined</span>
                  )}
                  {hasFaithIssue && (
                    <span style={styles.faithBadge} title={`Faithfulness: ${card.faithfulness}/100`}>⚠ check facts</span>
                  )}
                </div>
                <div style={styles.personaDesc}>{card.persona_description}</div>
              </div>
            </div>

            {/* Three-axis score dials */}
            <div style={styles.dialsRow}>
              <ScoreDial
                label="Distinctive"
                value={card.scores.distinctiveness}
                subtitle=""
                lowLabel="Generic"
                highLabel="Bold"
                delta={card.deltas.distinctiveness}
              />
              {card.scores.voice_match != null && (
                <ScoreDial
                  label="Voice"
                  value={card.scores.voice_match}
                  subtitle=""
                  lowLabel="Drifting"
                  highLabel="Yours"
                  delta={card.deltas.voice_match ?? undefined}
                  color="green"
                />
              )}
              <ScoreDial
                label="On-message"
                value={card.scores.on_message}
                subtitle=""
                lowLabel="Off"
                highLabel="Faithful"
                color="amber"
              />
            </div>

            {/* Unsupported claims warning */}
            {hasFaithIssue && card.unsupported_claims.length > 0 && (
              <div style={styles.faithWarning}>
                <strong>Unverified claims:</strong>{' '}
                {card.unsupported_claims.slice(0, 4).join(' · ')}
              </div>
            )}

            {/* Direction text */}
            <p style={styles.cardText}>{card.text}</p>

            {/* Summary (collapsible) */}
            {card.summary && (
              <button style={styles.summaryToggle} onClick={() => setExpanded(isExpanded ? null : card.persona)}>
                {isExpanded ? '▲ hide detail' : '▼ score detail'}
              </button>
            )}
            {isExpanded && card.summary && (
              <div style={styles.summaryText}>{card.summary}</div>
            )}

            {/* Copy button */}
            <button
              style={copied === card.persona ? { ...styles.copyBtn, ...styles.copyBtnDone } : styles.copyBtn}
              onClick={() => handleCopy(card.text, card.persona)}
            >
              {copied === card.persona ? 'Copied!' : 'Copy'}
            </button>
          </div>
        )
      })}
    </div>
  )
}

const styles: Record<string, React.CSSProperties> = {
  grid: { display: 'flex', flexDirection: 'column', gap: '14px' },
  card: {
    background: '#1a1d27', border: '1px solid #2e3350', borderRadius: '10px',
    padding: '18px', display: 'flex', flexDirection: 'column', gap: '10px',
  },
  skeleton: { gap: '10px', opacity: 0.5 },
  skeletonLine: {
    height: '12px', background: '#2e3350', borderRadius: '4px', width: '100%',
    animation: 'pulse 1.5s ease-in-out infinite',
  },
  cardHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '10px' },
  personaRow: { display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' },
  personaLabel: { fontSize: '13px', fontWeight: 700, color: '#6b74f8' },
  personaDesc: { fontSize: '11px', color: '#7c829e', marginTop: '2px' },
  refinedBadge: {
    fontSize: '10px', fontWeight: 600, color: '#6b74f8',
    background: 'rgba(107,116,248,0.12)', border: '1px solid rgba(107,116,248,0.3)',
    borderRadius: '4px', padding: '1px 6px',
  },
  faithBadge: {
    fontSize: '10px', fontWeight: 600, color: '#f5a623',
    background: 'rgba(245,166,35,0.1)', border: '1px solid rgba(245,166,35,0.3)',
    borderRadius: '4px', padding: '1px 6px',
  },
  dialsRow: {
    display: 'flex', gap: '4px', justifyContent: 'space-around',
    background: '#141720', borderRadius: '8px', padding: '12px 8px',
  },
  faithWarning: {
    fontSize: '11px', color: '#f5a623',
    background: 'rgba(245,166,35,0.07)', border: '1px solid rgba(245,166,35,0.2)',
    borderRadius: '6px', padding: '7px 10px',
  },
  cardText: { fontSize: '14px', color: '#c8cad8', lineHeight: 1.65, margin: 0 },
  summaryToggle: {
    alignSelf: 'flex-start', background: 'transparent', border: 'none',
    color: '#7c829e', fontSize: '11px', padding: '0', cursor: 'pointer',
  },
  summaryText: {
    fontSize: '11px', color: '#7c829e', lineHeight: 1.6,
    background: '#141720', borderRadius: '6px', padding: '8px 10px',
  },
  copyBtn: {
    alignSelf: 'flex-start', background: 'transparent', border: '1px solid #2e3350',
    borderRadius: '6px', color: '#7c829e', fontSize: '12px', fontWeight: 600,
    padding: '5px 12px', transition: 'border-color 0.15s, color 0.15s', cursor: 'pointer',
  },
  copyBtnDone: { borderColor: '#3ecf8e', color: '#3ecf8e' },
  empty: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
    gap: '12px', padding: '48px 24px', color: '#7c829e', textAlign: 'center', fontSize: '14px',
  },
  emptyIcon: { fontSize: '28px', color: '#2e3350' },
}
